import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Building2, Home, ImagePlus, LayoutDashboard, LogOut, MessageCircle, Plus, RefreshCw, Settings, Tag, Users, Pencil, Archive, Star, Upload, X, ShieldCheck } from 'lucide-react'
import '../styles.css'
import './admin.css'
import { adminApi, API_URL } from './api'

const PROPERTY_TYPES = ['Houses', 'Residential Stands', 'Commercial Buildings', 'Commercial Stands', 'Industrial Stands', 'Industrial Properties']
const STATUSES = ['draft', 'available', 'sold', 'archived']
const emptyProperty = { title: '', slug: '', property_type: 'Houses', location: '', price: '', bedrooms: '', rooms: '', stand_size: '', description: '', features: '', paperwork_status: '', status: 'draft', featured: false }

function Login({ onLogin }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const result = await adminApi.login(email, password); localStorage.setItem('lamaris_admin_token', result.access_token); onLogin(result.must_change_password) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <div className="admin-login"><div className="admin-login-card"><div className="admin-brand admin-login-brand"><span className="brand-mark"><Building2 size={22}/></span><span><strong>LAMARIS</strong><small>ADMIN</small></span></div><span className="kicker">SECURE MANAGEMENT</span><h1>Sign in to Lamaris</h1><p>Manage properties, listings and customer enquiries.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <div className="admin-alert error">{error}</div>}<button className="button primary full" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form><small className="admin-login-note">API: {API_URL}</small></div></div>
}

function ChangePassword({ user, onComplete, forced }) {
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  async function submit(event) { event.preventDefault(); setError(''); setSuccess(''); if (newPassword !== confirm) { setError('New passwords do not match'); return } setLoading(true); try { const result = await adminApi.changePassword(currentPassword, newPassword); localStorage.setItem('lamaris_admin_token', result.access_token); setSuccess('Password updated successfully.'); setTimeout(onComplete, 700) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <div className="admin-login"><div className="admin-login-card"><div className="admin-brand admin-login-brand"><span className="brand-mark"><ShieldCheck size={22}/></span><span><strong>LAMARIS</strong><small>SECURITY</small></span></div><span className="kicker">{forced ? 'FIRST LOGIN REQUIRED' : 'ACCOUNT SECURITY'}</span><h1>{forced ? 'Set your new password' : 'Change password'}</h1><p>{forced ? `Your temporary password must be replaced before continuing. ${user?.email || ''}` : 'Choose a new password for your administrator account.'}</p><form onSubmit={submit}><label>Current password<input type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} required autoComplete="current-password" /></label><label>New password<input type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} required minLength="12" autoComplete="new-password" /><small>At least 12 characters, including uppercase, lowercase and a number.</small></label><label>Confirm new password<input type="password" value={confirm} onChange={e => setConfirm(e.target.value)} required minLength="12" autoComplete="new-password" /></label>{error && <div className="admin-alert error">{error}</div>}{success && <div className="admin-alert success">{success}</div>}<button className="button primary full" disabled={loading}>{loading ? 'Updating…' : 'Set new password'}</button></form></div></div>
}

function Admin() {
  const [authenticated, setAuthenticated] = useState(Boolean(localStorage.getItem('lamaris_admin_token'))); const [section, setSection] = useState('Dashboard'); const [user, setUser] = useState(null); const [mustChange, setMustChange] = useState(false)
  const nav = [['Dashboard', LayoutDashboard], ['Properties', Home], ['Enquiries', MessageCircle], ['Blog', Tag], ['Media', ImagePlus], ['Team', Users], ['Settings', Settings]]
  useEffect(() => { if (authenticated) adminApi.me().then(result => { setUser(result); setMustChange(Boolean(result.must_change_password)) }).catch(() => { localStorage.removeItem('lamaris_admin_token'); setAuthenticated(false) }) }, [authenticated])
  if (!authenticated) return <Login onLogin={(required) => { setMustChange(Boolean(required)); setAuthenticated(true) }} />
  if (mustChange) return <ChangePassword user={user} forced onComplete={() => setMustChange(false)} />
  async function logout() { try { await adminApi.logout() } catch (_) {} localStorage.removeItem('lamaris_admin_token'); setAuthenticated(false); setUser(null); setMustChange(false) }
  return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="brand-mark"><Building2 size={20}/></span><span><strong>LAMARIS</strong><small>ADMIN</small></span></div><nav>{nav.map(([label, Icon]) => <button className={section === label ? 'active' : ''} onClick={() => setSection(label)} key={label}><Icon size={18}/>{label}</button>)}</nav><button className="admin-exit" onClick={logout}><LogOut size={17}/> Sign out</button><a className="admin-exit" href="./"><Home size={17}/> View website</a></aside><main className="admin-main"><header className="admin-header"><div><span className="kicker">LAMARIS MANAGEMENT</span><h1>{section}</h1>{user && <small>{user.email}</small>}</div>{section === 'Properties' && <button className="button primary" onClick={() => window.dispatchEvent(new CustomEvent('new-property'))}><Plus size={17}/> Add Property</button>}</header>{section === 'Dashboard' && <Dashboard onNavigate={setSection}/>} {section === 'Properties' && <Properties/>} {section === 'Enquiries' && <Enquiries/>} {section === 'Settings' && <SettingsPanel user={user}/>} {!['Dashboard','Properties','Enquiries','Settings'].includes(section) && <Placeholder section={section}/>}</main></div>
}

function Dashboard({ onNavigate }) {
  const [properties, setProperties] = useState([]); const [enquiries, setEnquiries] = useState([]); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([adminApi.properties('status='), adminApi.enquiries()]).then(([p,e]) => { setProperties(p); setEnquiries(e) }).catch(() => {}).finally(() => setLoading(false)) }, [])
  const counts = useMemo(() => ({ active: properties.filter(p => p.status === 'available').length, featured: properties.filter(p => p.featured && p.status === 'available').length, sold: properties.filter(p => p.status === 'sold' || p.status === 'archived').length, newEnquiries: enquiries.filter(e => e.status === 'new').length }), [properties,enquiries])
  const stats = [['Active listings',counts.active,'Manage properties'],['Featured deals',counts.featured,'Promoted listings'],['New enquiries',counts.newEnquiries,'Needs follow-up'],['Sold / archived',counts.sold,'Listing history']]
  return <><div className="admin-stats">{stats.map(([label,value,sub]) => <div className="stat" key={label}><small>{label}</small><strong>{loading ? '—' : value}</strong><span>{sub}</span></div>)}</div><div className="admin-columns"><section className="admin-panel"><div className="panel-heading"><div><strong>Recent enquiries</strong><small>Latest customer conversations</small></div><button className="text-button" onClick={() => onNavigate('Enquiries')}>View all</button></div>{enquiries.slice(0,5).map(e => <div className="enquiry" key={e.id}><MessageCircle/><div><strong>{e.name}</strong><small>{e.message}</small></div><span>{e.status}</span></div>)}{!loading && !enquiries.length && <div className="empty-small">No enquiries yet.</div>}</section><section className="admin-panel"><div className="panel-heading"><div><strong>Listing status</strong><small>Keep availability current</small></div></div>{['available','featured','sold','draft'].map(key => <div className="status-row" key={key}><span>{key[0].toUpperCase()+key.slice(1)}</span><strong>{loading ? '—' : key === 'featured' ? counts.featured : properties.filter(p => p.status === key).length}</strong></div>)}</section></div><section className="admin-panel workflow"><div><strong>Property publishing workflow</strong><p>Add details, upload photos, set price and availability, then publish. Public listings are read from the API.</p></div><button className="button primary" onClick={() => onNavigate('Properties')}><Plus size={17}/> Manage listings</button></section></>
}

function Properties() {
  const [items,setItems] = useState([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [editing,setEditing] = useState(null); const [search,setSearch] = useState(''); const [status,setStatus] = useState('all')
  const load = () => { setLoading(true); setError(''); adminApi.properties('status=').then(setItems).catch(e => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(() => { load(); const handler = () => setEditing({...emptyProperty}); window.addEventListener('new-property',handler); return () => window.removeEventListener('new-property',handler) },[])
  async function archive(id) { if (!confirm('Archive this property?')) return; try { await adminApi.archiveProperty(id); load() } catch(e) { setError(e.message) } }
  const filtered = items.filter(item => (status === 'all' || item.status === status) && `${item.title} ${item.location} ${item.property_type}`.toLowerCase().includes(search.toLowerCase()))
  return <>{error && <div className="admin-alert error">{error}</div>}<div className="property-toolbar"><div className="property-filters"><input placeholder="Search properties…" value={search} onChange={e => setSearch(e.target.value)}/><select value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></div><span>{loading ? 'Loading…' : `${filtered.length} listing${filtered.length === 1 ? '' : 's'}`}</span><button className="button secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div><section className="admin-panel property-table"><div className="table-head"><span>Property</span><span>Location</span><span>Status</span><span>Price</span><span>Actions</span></div>{filtered.map(item => <div className="table-row" key={item.id}><div><strong>{item.title}</strong><small>{item.property_type}{item.featured ? ' · Featured' : ''}</small></div><span>{item.location}</span><span className={`badge ${item.status}`}>{item.status}</span><span>{item.price || 'Price on enquiry'}</span><div className="row-actions"><button title="Edit" onClick={() => setEditing(item)}><Pencil size={16}/></button>{item.status !== 'archived' && <button title="Archive" onClick={() => archive(item.id)}><Archive size={16}/></button>}</div></div>)}{!loading && !filtered.length && <div className="empty-small">No matching properties.</div>}</section>{editing && <PropertyForm property={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load() }}/>}</>
}

function PropertyForm({ property,onClose,onSaved }) {
  const isNew = !property.id; const [form,setForm] = useState({...emptyProperty,...property,bedrooms:property.bedrooms ?? '',rooms:property.rooms ?? ''}); const [files,setFiles] = useState([]); const [saving,setSaving] = useState(false); const [error,setError] = useState(''); const [success,setSuccess] = useState('')
  const change = (key,value) => setForm(prev => ({...prev,[key]:value})); const slugify = value => value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); setSuccess(''); const payload = {...form,bedrooms:form.bedrooms === '' ? null : Number(form.bedrooms),rooms:form.rooms === '' ? null : Number(form.rooms),slug:form.slug || slugify(form.title)}; try { const saved = isNew ? await adminApi.createProperty(payload) : await adminApi.updateProperty(form.id,payload); for (const file of files) { const upload = await adminApi.uploadImage(file); await adminApi.attachImage(saved.id,upload.url,form.title) } setSuccess('Property saved successfully.'); setTimeout(onSaved,500) } catch(e) { setError(e.message) } finally { setSaving(false) } }
  return <div className="modal-backdrop"><div className="property-modal"><div className="modal-header"><div><span className="kicker">PROPERTY MANAGEMENT</span><h2>{isNew ? 'Add property' : 'Edit property'}</h2></div><button onClick={onClose}><X/></button></div><form onSubmit={submit} className="property-form"><div className="form-grid"><label>Title<input value={form.title} onChange={e => change('title',e.target.value)} required/></label><label>Property type<select value={form.property_type} onChange={e => change('property_type',e.target.value)}>{PROPERTY_TYPES.map(t => <option key={t}>{t}</option>)}</select></label><label>Location<input value={form.location} onChange={e => change('location',e.target.value)} required/></label><label>Price<input value={form.price || ''} onChange={e => change('price',e.target.value)} placeholder="e.g. USD 45,000"/></label><label>Bedrooms<input type="number" min="0" value={form.bedrooms} onChange={e => change('bedrooms',e.target.value)}/></label><label>Rooms<input type="number" min="0" value={form.rooms} onChange={e => change('rooms',e.target.value)}/></label><label>Stand size<input value={form.stand_size || ''} onChange={e => change('stand_size',e.target.value)} placeholder="e.g. 500 sqm"/></label><label>Status<select value={form.status} onChange={e => change('status',e.target.value)}>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></label></div><label>Description<textarea rows="4" value={form.description || ''} onChange={e => change('description',e.target.value)}/></label><label>Features<textarea rows="3" value={form.features || ''} onChange={e => change('features',e.target.value)} placeholder="Separate features with commas"/></label><label>Paperwork status<input value={form.paperwork_status || ''} onChange={e => change('paperwork_status',e.target.value)} placeholder="e.g. Council cession available"/></label><label className="check-label"><input type="checkbox" checked={Boolean(form.featured)} onChange={e => change('featured',e.target.checked)}/><span><Star size={16}/> Feature this listing</span></label><label className="upload-box"><Upload size={20}/><span>Upload property photos</span><small>JPEG, PNG or WebP · up to 10 MB each</small><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e => setFiles(Array.from(e.target.files || []))}/>{files.length > 0 && <strong>{files.length} photo{files.length === 1 ? '' : 's'} selected</strong>}</label>{error && <div className="admin-alert error">{error}</div>}{success && <div className="admin-alert success">{success}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving ? 'Saving…' : isNew ? 'Create listing' : 'Save changes'}</button></div></form></div></div>
}

function Enquiries() { const [items,setItems] = useState([]); useEffect(() => { adminApi.enquiries().then(setItems).catch(() => {}) },[]); return <section className="admin-panel"><div className="panel-heading"><div><strong>Customer enquiries</strong><small>Enquiries received from the website</small></div></div>{items.map(e => <div className="enquiry enquiry-large" key={e.id}><MessageCircle/><div><strong>{e.name} · {e.phone}</strong><small>{e.email || 'No email'} · {e.message}</small></div><span>{e.status}</span></div>)}{!items.length && <div className="empty-small">No enquiries yet.</div>}</section> }
function SettingsPanel({ user }) { const [changing,setChanging] = useState(false); return <div className="admin-empty"><div className="service-icon"><Settings/></div><h2>Account & Security</h2><p>{user?.email}</p><button className="button primary" onClick={() => setChanging(true)}>Change password</button>{changing && <ChangePassword user={user} onComplete={() => setChanging(false)}/>}</div> }
function Placeholder({section}) { return <div className="admin-empty"><div className="service-icon"><LayoutDashboard/></div><h2>{section} management</h2><p>This module will be connected to the same API-backed workflow as properties and enquiries.</p></div> }

createRoot(document.getElementById('admin-root')).render(<Admin/>)
